<!DOCTYPE html>
<html lang="{{ $currentLanguageInfo->code }}" @if ($currentLanguageInfo->direction == 1) dir="rtl" @endif>

<head>
  {{-- required meta tags --}}
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {{-- csrf-token for ajax request --}}
  <meta name="csrf-token" content="{{ csrf_token() }}">

  {{-- title --}}
  <title>@yield('pageHeading') {{ '| ' . $websiteInfo->website_title }}</title>

  <meta name="keywords" content="@yield('metaKeywords')">
  <meta name="description" content="@yield('metaDescription')">
  <meta name="theme-color" content="{{ $basicInfo->primary_color }}" />

  {{-- fav icon --}}
  <link rel="shortcut icon" type="image/png" href="{{ asset('assets/img/' . $websiteInfo->favicon) }}">
  <link rel="apple-touch-icon" href="{{ asset('assets/img/' . $websiteInfo->favicon) }}">

  {{-- include styles --}}
  @includeIf('frontend.partials.styles')
  <link rel="manifest" crossorigin="use-credentials" href="{{ asset('manifest.json') }}" />

  {{-- additional style --}}
  @yield('style')
</head>

<body>
  {{-- preloader start --}}
  <div class="preloader">
	
    <!--<div class="lds-ellipsis">
      <span></span>
      <span></span>
      <span></span>
    </div> -->
	<div class="loadingio-spinner-double-ring-c8y9vshnbz"><div class="ldio-5g0uz1bo7b">
<div></div>
<div></div>
<div><div></div></div>
<div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-5g0uz1bo7b {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-5g0uz1bo7b div { box-sizing: border-box!important }
.ldio-5g0uz1bo7b > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #eb3b27 transparent #eb3b27 transparent;
  animation: ldio-5g0uz1bo7b 1s linear infinite;
}

.ldio-5g0uz1bo7b > div:nth-child(2), .ldio-5g0uz1bo7b > div:nth-child(4) {
  width: 54px;
  height: 54px;
  top: 23px;
  left: 23px;
  animation: ldio-5g0uz1bo7b 1s linear infinite reverse;
}
.ldio-5g0uz1bo7b > div:nth-child(2) {
  border-color: transparent #f8b26a transparent #f8b26a
}
.ldio-5g0uz1bo7b > div:nth-child(3) { border-color: transparent }
.ldio-5g0uz1bo7b > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-5g0uz1bo7b > div:nth-child(3) div:before, .ldio-5g0uz1bo7b > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #eb3b27;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #eb3b27;
}
.ldio-5g0uz1bo7b > div:nth-child(3) div:after {
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #eb3b27;
}

.ldio-5g0uz1bo7b > div:nth-child(4) { border-color: transparent; }
.ldio-5g0uz1bo7b > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-5g0uz1bo7b > div:nth-child(4) div:before, .ldio-5g0uz1bo7b > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 15px;
  background: #f8b26a;
  border-radius: 50%;
  box-shadow: 0 46px 0 0 #f8b26a;
}
.ldio-5g0uz1bo7b > div:nth-child(4) div:after {
  left: -8px;
  top: 15px;
  box-shadow: 46px 0 0 0 #f8b26a;
}
.loadingio-spinner-double-ring-c8y9vshnbz {
    width: 50px;
    height: 50px;
    transform: translate(-50%, -50%);
    position: absolute;
    left: 50%;
    top: 50%;
}
.ldio-5g0uz1bo7b {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.5);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-5g0uz1bo7b div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

  </div>
  {{-- preloader end --}}


  @yield('content')

  {{-- back to top start --}}
  <a href="#" class="back-to-top"><i class="fas fa-angle-up"></i></a>
  {{-- back to top end --}}

  {{-- floating whatsapp button --}}
  @if ($basicInfo->whatsapp_status == 1 && $basicInfo->tawkto_status == 0)
    <div class="whatsapp-btn"></div>
  @endif

  {{-- tawk.to button --}}
  @if ($basicInfo->whatsapp_status == 0 && $basicInfo->tawkto_status == 1)
    @php
      $directLink = str_replace('tawk.to', 'embed.tawk.to', $basicInfo->tawkto_direct_chat_link);
      $directLink = str_replace('chat/', '', $directLink);
    @endphp

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
      "use strict";

      var Tawk_API = Tawk_API || {},
        Tawk_LoadStart = new Date();

      (function() {
        var s1 = document.createElement("script"),
          s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = '{{ $directLink }}';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
      })();
    </script>
    <!--End of Tawk.to Script-->
  @endif

  {{-- announcement popup --}}
  @includeIf('frontend.partials.popups')

  {{-- cookie alert --}}
  @if (!is_null($cookieAlertInfo) && $cookieAlertInfo->cookie_alert_status == 1)
    @include('cookie-consent::index')
  @endif


  {{-- include scripts --}}
  @includeIf('frontend.partials.scripts')

  {{-- additional script --}}
  @yield('script')
</body>

</html>
